### PR TITLE
Improve performance of OpenCMISS CellML

### PR DESCRIPTION
**Pull request by A1kmm**
Improve performance of OpenCMISS CellML

### CODE REVIEW

**Comment by chrispbradley** [comment]
@nickerso do you want to review this?

**Comment by nickerso** [comment]
commit fabe885 is unrelated to the purpose of this pull request and needs to be moved to its own pull request (and associated tracker item).

**Comment by A1kmm** [comment]
I don't think github lets you directly cherrypick what to put in pull requests. I could in theory make another branch with just that change, cherrypicked, but in this case, I wouldn't even be able to test that branch since it doesn't build without the first commit for me.

I think all of this is probably trying to use pull requests for something that they are not intended for; why not review the commits individually, and use git cherrypick to move those that are reviewed favourably into the central trunk?

**Comment by A1kmm** [comment]
In terms of the tracker item, I opened this one: https://tracker.physiomeproject.org/show_bug.cgi?id=3401

**Comment by nickerso** [comment]
Tracker item 3396 appears to address the underlying problem this code was working around. Is it worth changing to use the new API functions in the CellML API rather than implementing this change?

**Comment by A1kmm** [comment]
I think that the STL based code will still be more efficient, especially for mInitialValues, because it can index on exactly what OpenCMISS code wants to look up values by (i.e. which index in which array), while it is necessary to iterate through every variable to find the desired one if AnnoTools is used.

In terms of mVariableTypes and mVariableIndices, for n variables and m keys, STL indexing by the objid is O(log n), while AnnoTools is O(log m), so in asymptotically AnnoTools could be faster (since m is fixed, and n can increase with the size of the model). However, I expect that for practical values of n and m, this difference is likely entirely wiped out by overheads, especially if string annotations are used and they need to be parsed. Using object annotations rather than string annotations would avoid this, but it might be more messy than it is worth.

I would therefore suggest that changeset 2990e9a is still the best way to move forward.

**Comment by nickerso** [comment]
Commit fabe885 will need to be moved to a separate branch then, as it needs to be merged in with Chris' changes for getting things working under gcc 4.7 (i.e., the need to including unistd.h), which is different again to the changes in CMakeLists.txt which should really go in a separate branch and tracker item again. As per standard usage of git, github and the tracker by OpenCMISS developers.

As for commit 2990e9a, it looks ok to me but I need to test the performance. @A1kmm or @chrispbradley can you let me know where to grab the test case which demonstrated this issue initially.

**Comment by chrispbradley** [comment]
The example that caused problems was Monodomain_Shiqiang which is in my branch under examples/Bioelectrics.

**Comment by nickerso** [comment]
@A1kmm, I'm just wondering how you tested the code? I am unable to compile OpenCMISS(cellml) from this pull request with the current version of the CellML API in OpenCMISSExtras due to https://tracker.physiomeproject.org/show_bug.cgi?id=3220 (since there is now an additional dependency on IfaceCCGS.hpp in CellMLModelDefinition.hpp which reintroduces the problem from tracker item 3220). I have now updated the API code to the current head revision from GitHub which fixes that problem but the model used in @chrispbradley's test case fails as invalid CellML and therefore doesn't work at all.

I now see that @A1kmm has a corrected (?) version of the test case model on github, so I'll try that and see how things go.

**Comment by nickerso** [comment]
Given @A1kmm's comment above regarding commit 2990e9a performing better than the fixed up CellML API annotations, this seems like a good way to be going. I checked the performance, and the Monodomain_Shiqiang test example had a 22x speed up for the bits I was able to get to run (performing the actual simulation resulted in a floating point exception, but I understand the performance hit being addressed here was in setting up the CellML models prior to that).

With this pull request, however, there are a couple of issues scattered in the comments above. Firstly, commit fabe885  needs to be combined with @chrispbradley's work on OpenCMISS(cellml) getting it building with gcc 4.7 (i.e., commit fa87229).

Secondly, these changes will only build with a newer version of the CellML API than what is currently in OpenCMISSExtras. The CellML API in OpenCMISSExtras originated from a sourceforge mercurial repository which has now been migrated to a git repository on github. We probably need to discuss updating the OpenCMISSExtras CellML API code before pulling in these changes - there are some semi-serious side effects of doing this, like more recent versions of the API include better and more thorough checks on the CellML models, which can result in previously working models no longer working - see @A1kmm's version of the Monodomain_Shiqiang test example (see the unfortunately overwhelming commit https://github.com/A1kmm/opencmissexamples/commit/ccc5f1e, for example).

**Comment by chrispbradley** [comment]
OK, lets talk about it at the OpenCMISS meeting tomorrow.

**Comment by codecurve** [comment]
Note that Andrew has made it easier to see the changes that were required to the example, see  https://github.com/A1kmm/opencmissexamples/commit/45f9c9f130

**Comment by nickerso** [comment]
just to note that we discussed this pull request at the Auckland OpenCMISS meeting. Commit 2990e9a will be cherry picked rather than pulling in the entire pull request, but this will need to wait on @chrispbradley updating OpenCMISSExtras to include a more recent version of the CellML API code (he is currently updating most of the packages in OpenCMISSExtras).

**Comment by nickerso** [comment]
I have opened pull request 9 (https://github.com/OpenCMISS/cellml/pull/9) which merges the commits from this request with @chrispbradley's changes for gcc 4.7. Probably best to close this pull request now.

**Comment by chrispbradley** [comment]
OK. What is the plan with pull request 9? It will need the new CellML v 1.12 from extras? From you message there you were want people to test that before merging the svn branch. Does that mean that pull 9 should wait a bit?

**Comment by chrispbradley** [comment]
Closing as this pull request has been pulled in pull request 9  (OpenCMISS/cellml#9).

**Pull request closed without merging**
