### PR TITLE
Correct required CMake version

### PR DESCRIPTION
**Pull request by adamreeve**
hpc3 has CMake 2.6 installed so people have been having to compile their own CMake to get 2.8, but features from 2.8 aren't actually used and 2.6 works correctly.

@nickerso has said this should be fine.

### CODE REVIEW

**Comment by chrispbradley** [comment]
People can actually use the newer version by setting the environment variable USE_OPENCMISS_CMAKE. That said, if it is not being used then it shouldn't be mandated.

**Comment by adamreeve** [comment]
Ah right, I didn't realise it was in OpenCMISS extras too, I got Vickie to compile the latest CMake...

**Comment by chrispbradley** [comment]
Yes, the process now is to have each package that might otherwise be in a normal Linux build but be of a lesser version have its own repository. This is so that people don't have to download it if they don't need it. The opencmiss_programmer script will check if the environment variable is set and use the OpenCMISS extras version as appropriate.

**Comment by chrispbradley** [comment]
p.s. there is also an OpenCMISSExtras git as well in case hpc users have problems using the proxy from within the ABI.

**Comment by adamreeve** [comment]
Yes I did have to use that one as the one installed on hpc3 didn't work.

**Pull request merged**
